using System;
using System.Collections.Generic;
using System.IO;
using System.Xml;

namespace ASEva.Utility
{
    /// \~English
    /// <summary>
    /// (api:app=2.0.0) Generation's processing status
    /// </summary>
    /// \~Chinese
    /// <summary>
    /// (api:app=2.0.0) Generation的状态信息
    /// </summary>
    public enum GenerationProcessStatus
    {
        /// \~English
        /// <summary>
        /// Unknown (That generated by older application doesn't have status)
        /// </summary>
        /// \~Chinese
        /// <summary>
        /// 未知（在较老版本中输出的Generation不包括状态信息）
        /// </summary>
        Unknown,

        /// \~English
        /// <summary>
        /// Processing finished
        /// </summary>
        /// \~Chinese
        /// <summary>
        /// 处理完毕
        /// </summary>
        Finished,

        /// \~English
        /// <summary>
        /// Processing unfinished (Canceled by user or automatically skipped while processing)
        /// </summary>
        /// \~Chinese
        /// <summary>
        /// 未处理完毕（在处理过程中手动停止或卡死自动跳过导致）
        /// </summary>
        NotFinished,
    }

    /// \~English
    /// 
    /// \~Chinese
    /// <summary>
    /// (api:app=2.0.0) 读写Generation的信息文件(info.xml)
    /// </summary>
    public class GenerationInfo
    {
        /// \~English
        /// 
        /// \~Chinese
        /// <summary>
        /// 文件路径
        /// </summary>
        public String FilePath { get; set; }

        /// \~English
        /// 
        /// \~Chinese
        /// <summary>
        /// Generation ID
        /// </summary>
        public String GenerationID { get; set; }

        /// \~English
        /// 
        /// \~Chinese
        /// <summary>
        /// 状态信息
        /// </summary>
        public GenerationProcessStatus ProcessStatus { get; set; }

        /// \~English
        /// 
        /// \~Chinese
        /// <summary>
        /// 样本别名表
        /// </summary>
        public Dictionary<string, string> SampleAlias { get; set; }

        /// \~English
        /// 
        /// \~Chinese
        /// <summary>
        /// 创建Generation的软件版本信息（用于回溯）
        /// </summary>
        public Dictionary<string, Version> Versions { get; set; }

        /// \~English
        /// 
        /// \~Chinese
        /// <summary>
        /// Generation更新记录
        /// </summary>
        public Dictionary<DateTime, string> UpdateLogs { get; set; }

        /// \~English
        /// 
        /// \~Chinese
        /// <summary>
        /// (api:app=2.12.0) Generation生成时使用或覆盖的卫星Posix时间模型
        /// </summary>
        public PosixTimeModel GNSSPosixModel { get; set; }

        /// \~English
        /// 
        /// \~Chinese
        /// <summary>
        /// (api:app=2.12.0) Generation生成时主机是否配置为与授时服务器同步
        /// </summary>
        public bool HostSync { get; set; }

        /// \~English
        /// 
        /// \~Chinese
        /// <summary>
        /// (api:app=2.12.0) Generation生成时被配置为与授时服务器同步的所有客机同步ID
        /// </summary>
        public String[] GuestSyncIDs { get; set; }

        private GenerationInfo()
        {
        }

        /// \~English
        /// 
        /// \~Chinese
        /// <summary>
        /// 创建信息文件对象（仅创建对象，不写入文件）
        /// </summary>
        /// <param name="filePath">文件路径</param>
        /// <param name="generationID">Generation ID</param>
        /// <param name="status">状态信息</param>
        /// <param name="versions">生成Generation的软件版本信息</param>
        /// <returns>返回创建的对象</returns>
        public static GenerationInfo Create(String filePath, String generationID, GenerationProcessStatus status, Dictionary<string, Version> versions)
        {
            return Create(filePath, generationID, status, null, versions, null, null, false, null);
        }

        /// \~English
        /// 
        /// \~Chinese
        /// <summary>
        /// 创建信息文件对象（仅创建对象，不写入文件）
        /// </summary>
        /// <param name="filePath">文件路径</param>
        /// <param name="generationID">Generation ID</param>
        /// <param name="status">状态信息</param>
        /// <param name="sampleAlias">样本别名表</param>
        /// <param name="versions">生成Generation的软件版本信息</param>
        /// <param name="updateLogs">Generation更新记录</param>
        /// <returns>返回创建的对象</returns>
        public static GenerationInfo Create(String filePath, String generationID, GenerationProcessStatus status, Dictionary<string, string> sampleAlias, Dictionary<string, Version> versions, Dictionary<DateTime, string> updateLogs)
        {
            return Create(filePath, generationID, status, sampleAlias, versions, updateLogs, null, false, null);
        }

        /// \~English
        /// 
        /// \~Chinese
        /// <summary>
        /// (api:app=2.12.0) 创建信息文件对象（仅创建对象，不写入文件）
        /// </summary>
        /// <param name="filePath">文件路径</param>
        /// <param name="generationID">Generation ID</param>
        /// <param name="status">状态信息</param>
        /// <param name="sampleAlias">样本别名表</param>
        /// <param name="versions">生成Generation的软件版本信息</param>
        /// <param name="updateLogs">Generation更新记录</param>
        /// <param name="gnssPosixModel">Generation生成时使用或覆盖的卫星Posix时间模型</param>
        /// <param name="hostSync">Generation生成时主机是否配置为与授时服务器同步</param>
        /// <param name="guestSyncIDs">Generation生成时被配置为与授时服务器同步的所有客机同步ID</param>
        /// <returns>返回创建的对象</returns>
        public static GenerationInfo Create(String filePath, String generationID, GenerationProcessStatus status, Dictionary<string, string> sampleAlias, Dictionary<string, Version> versions, Dictionary<DateTime, string> updateLogs, PosixTimeModel gnssPosixModel, bool hostSync, String[] guestSyncIDs)
        {
            if (filePath == null || filePath.Length == 0 || generationID == null || generationID.Length == 0) return null;

            var info = new GenerationInfo();
            info.FilePath = filePath;
            info.GenerationID = generationID;
            info.ProcessStatus = status;
            info.SampleAlias = sampleAlias;
            info.Versions = versions;
            info.UpdateLogs = updateLogs;
            info.GNSSPosixModel = gnssPosixModel;
            info.HostSync = hostSync;
            info.GuestSyncIDs = guestSyncIDs;

            return info;
        }

        /// \~English
        /// 
        /// \~Chinese
        /// <summary>
        /// 从已有信息文件中读取
        /// </summary>
        /// <param name="filePath">文件路径</param>
        /// <returns>返回创建的对象</returns>
        public static GenerationInfo Load(String filePath)
        {
            if (filePath == null || filePath.Length == 0) return null;

            var defaultGenID = Path.GetFileNameWithoutExtension(Path.GetDirectoryName(filePath));
            if (defaultGenID == null || defaultGenID.Length == 0) return null;

            GenerationInfo info = null;
            try
            {
                var xml = new XmlDocument();
                xml.Load(filePath);
                var attribs = xml.DocumentElement.Attributes;

                info = new GenerationInfo();

                if (attribs["gen_id"] != null)
                {
                    info.GenerationID = attribs["gen_id"].Value;
                }
                else
                {
                    info.GenerationID = defaultGenID;
                }

                if (attribs["finished"] != null)
                {
                    info.ProcessStatus = attribs["finished"].Value == "yes" ? GenerationProcessStatus.Finished : GenerationProcessStatus.NotFinished;
                }
                else
                {
                    info.ProcessStatus = GenerationProcessStatus.Unknown;
                }

                info.SampleAlias = new Dictionary<string, string>();
                var aliasNodes = xml.DocumentElement.GetElementsByTagName("alias");
                foreach (XmlElement aliasNode in aliasNodes)
                {
                    info.SampleAlias[aliasNode.Attributes["sample"].Value] = aliasNode.InnerText;
                }

                info.Versions = new Dictionary<string, Version>();
                var versionNodes = xml.DocumentElement.GetElementsByTagName("version");
                foreach (XmlElement versionNode in versionNodes)
                {
                    info.Versions[versionNode.Attributes["key"].Value] = Version.Parse(versionNode.InnerText);
                }

                info.UpdateLogs = new Dictionary<DateTime, string>();
                var updateNodes = xml.DocumentElement.GetElementsByTagName("update");
                foreach (XmlElement updateNode in updateNodes)
                {
                    info.UpdateLogs[DateTime.ParseExact(updateNode.Attributes["time"].Value, "yyyy-MM-dd-HH-mm-ss", null)] = updateNode.InnerText;
                }

                try
                {
                    if (attribs["start_posix_gnss"] != null && attribs["time_ratio_gnss"] != null)
                    {
                        info.GNSSPosixModel = new PosixTimeModel
                        {
                            StartPosix = Convert.ToUInt64(attribs["start_posix_gnss"].Value),
                            TimeRatio = Convert.ToDouble(attribs["time_ratio_gnss"].Value),
                        };
                    }
                    else info.GNSSPosixModel = null;
                }
                catch (Exception) { info.GNSSPosixModel = null; }

                if (attribs["host_sync"] != null)
                {
                    info.HostSync = attribs["host_sync"].Value == "yes";
                }
                else info.HostSync = false;

                var guestSyncList = new List<String>();
                foreach (XmlElement guestSyncNode in xml.DocumentElement.GetElementsByTagName("guest_sync"))
                {
                    if (guestSyncNode.InnerText.Length > 0) guestSyncList.Add(guestSyncNode.InnerText);
                }
                info.GuestSyncIDs = guestSyncList.ToArray();
            }
            catch (Exception) { }

            if (info == null)
            {
                info = new GenerationInfo()
                {
                    GenerationID = defaultGenID,
                    ProcessStatus = GenerationProcessStatus.Unknown,
                };
            }

            info.FilePath = filePath;
            return info;
        }

        /// \~English
        /// 
        /// \~Chinese
        /// <summary>
        /// 保存信息文件
        /// </summary>
        public void Save()
        {
            if (FilePath == null) return;
            if (ProcessStatus == GenerationProcessStatus.Unknown) return;

            try
            {
                var root = Path.GetDirectoryName(FilePath);
                if (!Directory.Exists(root)) Directory.CreateDirectory(root);
            }
            catch (Exception) { return; }

            var xml = new XmlDocument();
            xml.AppendChild(xml.CreateXmlDeclaration("1.0", "utf-8", null));
            var rootNode = xml.AppendChild(xml.CreateElement("root")) as XmlElement;

            rootNode.Attributes.Append(xml.CreateAttribute("gen_id")).Value = GenerationID;
            rootNode.Attributes.Append(xml.CreateAttribute("finished")).Value = ProcessStatus == GenerationProcessStatus.Finished ? "yes" : "no";

            if (SampleAlias != null)
            {
                foreach (var alias in SampleAlias)
                {
                    var aliasNode = rootNode.AppendChild(xml.CreateElement("alias")) as XmlElement;
                    aliasNode.Attributes.Append(xml.CreateAttribute("sample")).Value = alias.Key;
                    aliasNode.InnerText = alias.Value;
                }
            }

            if (Versions != null)
            {
                foreach (var item in Versions)
                {
                    var versionNode = rootNode.AppendChild(xml.CreateElement("version")) as XmlElement;
                    versionNode.Attributes.Append(xml.CreateAttribute("key")).Value = item.Key;
                    versionNode.InnerText = item.Value.ToString();
                }
            }

            if (UpdateLogs != null)
            {
                foreach (var update in UpdateLogs)
                {
                    var updateNode = rootNode.AppendChild(xml.CreateElement("update")) as XmlElement;
                    updateNode.Attributes.Append(xml.CreateAttribute("time")).Value = update.Key.ToString("yyyy-MM-dd-HH-mm-ss");
                    updateNode.InnerText = update.Value;
                }
            }

            if (GNSSPosixModel != null)
            {
                rootNode.Attributes.Append(xml.CreateAttribute("start_posix_gnss")).Value = GNSSPosixModel.StartPosix.ToString();
                rootNode.Attributes.Append(xml.CreateAttribute("time_ratio_gnss")).Value = GNSSPosixModel.TimeRatio.ToString();
            }

            rootNode.Attributes.Append(xml.CreateAttribute("host_sync")).Value = HostSync ? "yes" : "no";

            if (GuestSyncIDs != null)
            {
                foreach (var id in GuestSyncIDs)
                {
                    if (id.Length > 0) rootNode.AppendChild(xml.CreateElement("guest_sync")).InnerText = id;
                }
            }

            try
            {
                xml.Save(FilePath);
                return;
            }
            catch (Exception) {}

            if (File.Exists(FilePath))
            {
                try
                {
                    File.Delete(FilePath);
                    xml.Save(FilePath);
                }
                catch (Exception) {}
            }
        }
    }
}
